name: 'Pushinator action'
description: 'Send a push notification to your devices'
inputs:
  channelId:
    description: 'The ID of the channel to send the notification to'
    required: true
  apiToken:
    description: 'The API key to use to send the notification'
    required: true
  notification:
    description: 'The notification to send'
    required: true

outputs:
  result:
    description: 'The result of the action'

runs:
  using: 'node20'
  main: 'index.ts'